packages:
  - apps/*
  - packages/*
catalog:
  "@actions/exec": ^1.1.1
  "@apollo/client": ^3.11.7
  "@aws-sdk/client-s3": ^3.645.0
  "@aws-sdk/lib-storage": ^3.645.0
  "@babel/core": ^7.25.2
  "@babel/eslint-parser": ^7.25.1
  "@babel/preset-env": ^7.25.4
  "@babel/preset-react": ^7.24.7
  "@babel/register": ^7.24.6
  "@babel/runtime": ^7.25.0
  "@changesets/changelog-github": ^0.5.0
  "@changesets/cli": ^2.27.8
  "@commons-ui/legacy": npm:@commons-ui/core@^0.1.0
  "@commons-ui/core": ^0.1.0
  "@emotion/cache": ^11.13.1
  "@emotion/react": ^11.13.3
  "@emotion/server": ^11.11.0
  "@emotion/styled": ^11.13.0
  "@eslint/compat": ^1.1.2
  "@eslint/eslintrc": ^3.2.0
  "@eslint/js": ^9.16.0
  "@googlemaps/react-wrapper": ^1.1.42
  "@material-ui/codemod": ^4.5.1
  "@mdx-js/loader": ^3.0.1
  "@mdx-js/mdx": ^3.0.1
  "@mdx-js/react": ^3.0.1
  "@mui/icons-material": ^6.4.0
  "@mui/material": ^6.4.0
  "@mui/material-nextjs": ^6.3.1
  "@mui/utils": ^6.4.0
  "@mui/x-date-pickers": ^7.15.0
  "@mui/x-tree-view": ^7.15.0
  "@next/env": ^15.0.3
  "@next/eslint-plugin-next": ^15.0.3
  "@next/mdx": ^15.0.3
  "@next/third-parties": ^15.0.3
  "@nivo/core": ^0.84.0
  "@nivo/pie": ^0.84.0
  "@nivo/tooltip": ^0.84.0
  "@nivo/waffle": ^0.84.0
  "@payloadcms/bundler-webpack": ^1.0.7
  "@payloadcms/db-mongodb": ^1.7.2
  "@payloadcms/live-preview": ^0.2.2
  "@payloadcms/live-preview-react": ^0.2.0
  "@payloadcms/plugin-cloud-storage": ^1.1.3
  "@payloadcms/plugin-nested-docs": ^1.0.12
  "@payloadcms/plugin-sentry": ^0.0.6
  "@payloadcms/plugin-seo": ^2.3.2
  "@payloadcms/richtext-slate": ^1.5.2
  "@playwright/test": ^1.47.2
  "@react-spring/web": ^9.7.4
  "@reactour/tour": ^3.7.0
  "@sendgrid/mail": ^8.1.3
  "@sentry/nextjs": ^8.28.0
  "@storybook/addon-essentials": ^8.2.9
  "@storybook/addon-interactions": ^8.2.9
  "@storybook/addon-links": ^8.2.9
  "@storybook/blocks": ^8.2.9
  "@storybook/cli": ^8.2.9
  "@storybook/nextjs": ^8.2.9
  "@storybook/react": ^8.2.9
  "@storybook/test": ^8.2.9
  "@svgr/webpack": ^8.1.0
  "@swc/core": ^1.7.23
  "@testing-library/dom": ^10.4.0
  "@testing-library/jest-dom": ^6.5.0
  "@testing-library/react": ^16.0.1
  "@types/express": ^4.17.21
  "@types/better-sqlite3": "^7.6.11"
  "@types/jest": ^29.5.12
  "@types/mdx": ^2.0.13
  "@types/node": ^20.14.14
  "@types/nodemailer-sendgrid": ^1.0.3
  "@types/react": ^18.3.5
  "@types/react-dom": ^18.3.0
  ace-builds: ^1.36.2
  airtable: ^0.12.2
  apollo-link-rest: ^0.9.0
  aws-sdk: ^2.1689.0
  babel-jest: ^29.7.0
  babel-loader: ^9.1.3
  babel-plugin-transform-imports: ^2.0.0
  better-sqlite3: "^11.2.1"
  camelcase-keys: ^9.1.3
  clsx: ^2.1.1
  crawler-user-agents: ^1.0.146
  css-loader: ^7.1.2
  d3-format: ^3.1.0
  date-fns: ^4.1.0
  deepmerge: ^4.3.1
  dotenv: ^16.4.5
  eslint: ^9.0.0
  eslint-config-airbnb: ^19.0.4
  eslint-config-next: ^15.0.3
  eslint-config-prettier: ^9.1.0
  eslint-config-turbo: ^2.1.1
  eslint-import-resolver-babel-module: ^5.3.2
  eslint-import-resolver-jsconfig: ^1.1.0
  eslint-import-resolver-webpack: ^0.13.9
  eslint-import-resolver-typescript: ^3.6.3
  eslint-plugin-import: ^2.29.1
  eslint-plugin-jest: ^28.8.3
  eslint-plugin-jest-dom: ^5.4.0
  eslint-plugin-json: ^4.0.1
  eslint-plugin-jsx-a11y: ^6.10.0
  eslint-plugin-markdown: ^5.1.0
  eslint-plugin-mdx: ^3.1.5
  eslint-plugin-module-resolver: ^1.5.0
  eslint-plugin-playwright: ^2.1.0
  eslint-plugin-prettier: ^5.2.1
  eslint-plugin-react: ^7.35.2
  eslint-plugin-react-hooks: ^4.6.2
  eslint-plugin-testing-library: ^6.2.2
  express: ^4.19.2
  fast-equals: ^5.0.1
  form-data: ^4.0.0
  formik: ^2.4.6
  formik-mui: ^5.0.0-alpha.1
  formik-mui-lab: ^1.0.0
  googleapis: ^133.0.0
  graphql: ^15.9.0
  globals: ^15.12.0
  graphql-anywhere: ^4.2.8
  husky: ^8.0.3
  identity-obj-proxy: ^3.0.0
  jest: ^29.7.0
  jest-environment-jsdom: ^29.7.0
  js-yaml: ^4.1.0
  jscodeshift: ^0.15.2
  jsdom: ^24.1.3
  jwt-decode: ^4.0.0
  leaflet: ^1.9.4
  lint-staged: ^15.2.10
  lodash: ^4.17.21
  migrate-mongo: ^11.0.0
  monaco-editor: ^0.51.0
  next: ^15.0.3
  next-auth: ^4.24.7
  next-images: ^1.8.5
  next-seo: ^6.6.0
  next-sitemap: ^1.9.12
  nodemailer-sendgrid: ^1.0.3
  papaparse: ^5.4.1
  parse-numeric-range: ^1.3.0
  payload: 2.30.0
  plaiceholder: ^2.5.0
  prettier: ^3.3.3
  prop-types: ^15.8.1
  qs: ^6.13.0
  react: ^18.3.1
  react-ace: ^11.0.1
  react-dom: ^18.3.1
  react-copy-to-clipboard: ^5.1.0
  react-leaflet: ^4.2.1
  react-multi-carousel: ^2.8.5
  react-rotating-text: ^1.4.1
  react-share: ^5.1.0
  react-swipeable-views-react-18-fix: ^0.14.1
  react-test-renderer: ^18.3.1
  react-vega: ^7.6.0
  reading-time: ^1.5.0
  rehype-autolink-headings: ^7.1.0
  rehype-pretty-code: ^0.14.0
  rehype-slug: ^6.0.0
  remark-frontmatter: ^5.0.0
  remark-mdx-frontmatter: ^5.0.0
  require-from-string: ^2.0.2
  robots-txt-parse: ^2.0.1
  scheduler: ^0.23.2
  sharp: ^0.33.5
  shiki: ^1.18.0
  simplebar-react: ^3.2.6
  slate: ^0.103.0
  sqlite: ^5.1.1
  sqlite3: ^5.1.7
  storybook: ^8.2.9
  svg-url-loader: ^8.0.0
  swr: ^2.2.5
  tiny-warning: ^1.0.3
  tsc-alias: ^1.8.10
  tsconfig-paths: ^4.2.0
  tsx: ^4.19.1
  typescript: ^5.5.4
  typescript-eslint: ^8.16.0
  turbo: ^2.1.1
  vega: ^5.30.0
  vega-embed: ^6.26.0
  vega-lite: ^5.21.0
  vega-tooltip: ^0.34.0
  victory: ^36.9.2
  video.js: ^8.17.3
  videojs-youtube: ^3.0.1
  webpack: ^5.93.0
  xlsx: ^0.18.5
catalogs:
  # @mui/styles was deprecated with the release of MUI Core v5 in late 2021
  # @mui/styles is not compatible with React.StrictMode or React 18, and it will not be updated.
  # @see: https://mui.com/system/styles/basics/
  # climatemappedafrica, pesayetu and promisetracker still use @mui/styles
  mui-styles:
    "@mui/icons-material": ^5.16.6
    "@mui/lab": ^5.0.0-alpha.155
    "@mui/material": ^5.16.6
    "@mui/styles": ^5.16.6
    "@mui/utils": ^5.16.6
