const babelParser = require("@babel/eslint-parser");
const js = require("@eslint/js");
const turboConfig = require("eslint-config-turbo/flat");
const importPlugin = require("eslint-plugin-import");
const pluginJest = require("eslint-plugin-jest");
const jestDom = require("eslint-plugin-jest-dom");
const json = require("eslint-plugin-json");
const jsxA11y = require("eslint-plugin-jsx-a11y");
const markdown = require("eslint-plugin-markdown");
const playwright = require("eslint-plugin-playwright");
const reactPlugin = require("eslint-plugin-react");
const reactHooks = require("eslint-plugin-react-hooks");
const testingLibrary = require("eslint-plugin-testing-library");
const globals = require("globals");

const { importOrderRule } = require("./shared");

const codeFiles = ["**/*.{js,mjs,cjs,jsx}"];
const testFiles = [
  "**/*.test.{js,jsx,ts,tsx}",
  "**/jest.setup.{js,jsx,ts,tsx}",
];
const playwrightFiles = ["**/*.spec.{js,jsx,ts,tsx}"];
// eslint-config-turbo publishes a default export under CJS in this environment.
const turbo = turboConfig.default ?? turboConfig;

module.exports = [
  {
    ignores: [
      "**/node_modules",
      "**/.pnp",
      "**/.pnp.js",
      "**/.pnpm-debug.log",
      "**/dist/",
      "**/coverage",
      "**/.next/",
      "**/out/",
      "**/build/",
      "**/.DS_Store",
      "**/*.pem",
      "**/npm-debug.log*",
      "**/yarn-debug.log*",
      "**/yarn-error.log*",
      "**/.vercel",
      "**/.now",
      "**/.turbo",
      "**/test-results/",
      "**/playwright-report/",
      "**/next.config.mjs",
      "**/public/",
      "**/build",
      "**/contrib/",
      "**/scripts/",
      "**/src/app/(payload)/admin/importMap.js",
    ],
  },
  js.configs.recommended,
  ...markdown.configs.recommended,
  json.configs.recommended,
  // Enforce that env vars used in code are declared in turbo.json pipeline
  // configuration, ensuring correct cache invalidation in Turbo builds.
  ...turbo,
  {
    linterOptions: {
      // Warn on stale eslint-disable comments so they don't accumulate silently.
      reportUnusedDisableDirectives: "warn",
    },
  },
  {
    files: codeFiles,
    plugins: {
      import: importPlugin,
      "jsx-a11y": jsxA11y,
      react: reactPlugin,
      "react-hooks": reactHooks,
    },

    languageOptions: {
      parser: babelParser,
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
      },

      parserOptions: {
        requireConfigFile: false,
        ecmaFeatures: {
          jsx: true,
        },

        babelOptions: {
          presets: ["@babel/preset-react"],
        },

        allowImportExportEverywhere: true,
      },
    },

    settings: {
      react: {
        version: "detect",
      },
    },

    rules: {
      ...jsxA11y.flatConfigs.recommended.rules,
      ...reactPlugin.configs.flat.recommended.rules,
      ...reactPlugin.configs.flat["jsx-runtime"].rules,
      ...reactHooks.configs.recommended.rules,
      curly: ["error", "all"],
      "import/order": importOrderRule,
      "jsx-a11y/no-autofocus": "off",
      "no-restricted-imports": [
        "error",
        {
          patterns: ["@mui/*/*/*", "!@mui/material/test-utils/*"],
        },
      ],
      "no-constant-binary-expression": "warn",

      "react/jsx-filename-extension": [
        1,
        {
          extensions: [".js", ".jsx"],
        },
      ],
      "react/display-name": "off",
      "react/jsx-props-no-spreading": "off",
      "react/prop-types": "off",
      "react/react-in-jsx-scope": "off",
      "react/require-default-props": "off",
      "react-hooks/exhaustive-deps": "off",
      "no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          caughtErrors: "none",
          ignoreRestSiblings: true,
          varsIgnorePattern: "^(React|_)$",
        },
      ],
    },
  },
  {
    files: testFiles,
    ...pluginJest.configs["flat/recommended"],
    languageOptions: {
      globals: {
        ...pluginJest.environments.globals.globals,
        ...globals.browser,
        ...globals.jest,
        ...globals.node,
      },
    },
  },
  {
    files: testFiles,
    ...jestDom.configs["flat/recommended"],
  },
  {
    files: testFiles,
    ...testingLibrary.configs["flat/react"],
  },
  {
    files: testFiles,
    rules: {
      "jest-dom/prefer-empty": "off",
      "jest-dom/prefer-in-document": "off",
      "testing-library/no-container": "off",
      "testing-library/no-node-access": "off",
      "testing-library/prefer-screen-queries": "off",
      "testing-library/render-result-naming-convention": "off",
    },
  },
  {
    // .snap.js files are autogenerated by jest and may contain irregular
    // whitespace in string templates
    files: ["**/*.snap.js"],
    rules: {
      "no-irregular-whitespace": ["error", { skipTemplates: true }],
    },
  },
  {
    files: playwrightFiles,
    ...playwright.configs["flat/recommended"],
  },
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },
];
