module.exports = {
  extends: [
    "eslint:recommended",
    "plugin:markdown/recommended",
    "plugin:json/recommended",
    // airbnb enables: eslint-plugin-import, eslint-plugin-react,
    //                 eslint-plugin-react-hooks, and eslint-plugin-jsx-a11y
    "airbnb",
    "airbnb/hooks",
    "plugin:prettier/recommended",
  ],
  parser: "@babel/eslint-parser",
  parserOptions: {
    requireConfigFile: false,
    sourceType: "module",
    babelOptions: {
      presets: ["@babel/preset-react"],
    },
    allowImportExportEverywhere: true,
  },
  plugins: ["jest-dom", "testing-library"],
  rules: {
    "import/order": [
      "error",
      {
        alphabetize: {
          order: "asc",
          caseInsensitive: true,
        },
        "newlines-between": "always",
      },
    ],
    // https://mui.com/guides/minimizing-bundle-size/#option-1
    "no-restricted-imports": [
      "error",
      {
        patterns: ["@mui/*/*/*", "!@mui/material/test-utils/*"],
      },
    ],
    "react/jsx-filename-extension": [
      1,
      {
        extensions: [".js"],
      },
    ],
    "react/jsx-props-no-spreading": "off",
    "react/react-in-jsx-scope": "off",
    "react/prop-types": "off",
  },
  settings: {
    "import/resolver": {
      jsconfig: {
        config: "jsconfig.json",
      },
    },
  },
  overrides: [
    {
      files: ["**/*.test.js"],
      extends: [
        "plugin:jest/recommended",
        "plugin:jest-dom/recommended",
        "plugin:testing-library/react",
      ],
    },
    {
      // .snap.js files are autogenerated by jest and may contain irregular
      // whitespace in string templates
      files: ["**/*.snap.js"],
      rules: {
        "no-irregular-whitespace": ["error", { skipTemplates: true }],
      },
    },
    {
      files: ["**/*.spec.js"],
      extends: ["plugin:playwright/playwright-test"],
    },
  ],
};
