name: Continuous Integration

on:
  workflow_call:

jobs:
  ci:
    name: Format, Lint and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
      - name: Setup PNPM [Install]
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          run_install: false

      - name: Setup PNPM [Path]
        id: pnpm-path
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup PNPM [Cache]
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-path.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # Looks like to use pnpm cache, setup-node must run after pnpm/action-setup
      # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: "package.json"

      - name: Setup PNPM [Confirm]
        run: pnpm --version

      - name: Setup dependencies
        run: pnpm install

      - name: Setup dependencies [Playwright browsers]
        run: npx playwright install --with-deps

      - name: Format
        run: pnpm format-check

      - name: Lint
        run: pnpm lint-check

      - name: "Test [unit: Jest]"
        run: pnpm jest

      # PromiseTracker seems to build success but then "hang".
      # TODO(kilemensi): Investigate promisetrakcer
      - name: Build
        run: pnpm build --filter=promisetracker^...

      - name: "Test [integration: Playwright]"
        run: pnpm playwright --filter=promisetracker^...
