name: Code for Africa App
on:
  push:
    branches: [dokku-deployment]

env:
  IMAGE_NAME: "codeforafrica/cfa-ui"
  PACKAGE_PATH: "codeforafrica"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up Node since it's required by version-check
      # https://github.com/EndBug/version-check#github-workflow
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          build-args: |
              PACKAGE_PATH=${{ env.PACKAGE_PATH }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          context: .
          push: false
          tags: "${{ env.IMAGE_NAME }}:latest"
