name: Code for Africa | Deploy | DEV APP

on:
  push:
    branches: [develop]
    paths:
      - "apps/codeforafrica/**"
      - "Dockerfile.codeforafrica"
      - ".github/**"
concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true
env:
  DOKKU_REMOTE_BRANCH: "master"
  DOKKU_REMOTE_URL: "ssh://azureuser@ui-1.dev.codeforafrica.org"
  IMAGE_NAME: "codeforafrica/codeforafrica-ui"
  NEXT_PUBLIC_APP_URL: "https://codeforafrica-ui.dev.codeforafrica.org"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  APP_NAME: codeforafrica-ui

jobs:
  review_app:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18]
        os: [ubuntu-latest]
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          path: /tmp/.buildx-cache
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          build-args: |
            MONGODB_URL=${{ secrets.CODEFORAFRICA_MONGO_URL }}/${{ env.APP_NAME }}
            NEXT_PUBLIC_APP_URL=${{ env.NEXT_PUBLIC_APP_URL }}
            PAYLOAD_SECRET=${{ secrets.CODEFORAFRICA_PAYLOAD_SECRET_KEY }}
            GHOST_URL=${{ secrets.GHOST_URL }}
            GHOST_API_KEY=${{ secrets.GHOST_API_KEY }}
            NEXT_PUBLIC_APP_LOGO_URL=${{ secrets.NEXT_PUBLIC_APP_CFA_LOGO_URL }}
            NEXT_PUBLIC_APP_NAME=${{ secrets.NEXT_PUBLIC_APP_CFA_NAME }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          context: .
          file: ./Dockerfile.codeforafrica
          push: true
          tags: "${{ env.IMAGE_NAME }}:${{ github.sha }}"

      - name: Push to Dokku
        uses: dokku/github-action@v1.4.0
        with:
          git_remote_url: ${{ env.DOKKU_REMOTE_URL }}/${{ env.APP_NAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
