name: codeforafrica.org | Release
on:
  push:
    branches: ["main"]

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  IMAGE_FILE_LOCATION: "./apps/codeforafrica/contrib/dokku/Dockerfile"
  VERSION_FILE_LOCATION: "./apps/codeforafrica/package.json"

jobs:
  build:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.4.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm bump ${{ env.VERSION_FILE_LOCATION }} ${{ env.IMAGE_FILE_LOCATION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
