name: Pesayetu | Deploy | DEV

on:
  push:
    branches: [fix/docker-build]
    paths:
      - "apps/pesayetu/**"
      - "Dockerfile.pesayetu"
      - ".github/workflows/pesayetu-deploy-dev.yml"

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

env:
  APP_NAME: pesayetu-ui
  DOKKU_REMOTE_BRANCH: "master"
  DOKKU_REMOTE_URL: "ssh://azureuser@ui-1.dev.codeforafrica.org"
  IMAGE_NAME: "codeforafrica/pesayetu-ui"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NEXT_PUBLIC_APP_URL: "https://pesayetu-ui.dev.codeforafrica.org"
  SENTRY_ENVIRONMENT: "development"

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.14]
        os: [ubuntu-latest]
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          path: /tmp/.buildx-cache
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            WORDPRESS_URL=${{ secrets.PESAYETU_WORDPRESS_URL }}
            WORDPRESS_MULTISITE_PREFIX=${{ secrets.PESAYETU_WORDPRESS_MULTISITE_PREFIX }}
            WORDPRESS_PREVIEW_SECRET=${{ secrets.PESAYETU_WORDPRESS_PREVIEW_SECRET }}
            WORDPRESS_APPLICATION_USERNAME=${{ secrets.PESAYETU_WORDPRESS_APPLICATION_USERNAME }}
            WORDPRESS_APPLICATION_PASSWORD=${{ secrets.PESAYETU_WORDPRESS_APPLICATION_PASSWORD }}
            JWT_SECRET_KEY=${{ secrets.PESAYETU_JWT_SECRET_KEY }}
            HURUMAP_API_URL=${{ secrets.PESAYETU_HURUMAP_API_URL }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_ENVIRONMENT=${{ env.SENTRY_ENVIRONMENT }}
            SENTRY_ORG=${{ secrets.SENTRY_ORG }}
            SENTRY_PROJECT=${{ secrets.PESAYETU_SENTRY_PROJECT }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          context: .
          target: pesayetu-runner
          push: true
          tags: "${{ env.IMAGE_NAME }}:${{ github.sha }}"

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Push to Dokku
        uses: dokku/github-action@v1.4.0
        with:
          git_remote_url: ${{ env.DOKKU_REMOTE_URL }}/${{ env.APP_NAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
