name: Push to Dokku

on:
  workflow_call:
    inputs:
      remote_url:
        required: true
        type: string
        description: "The remote URL to push to"
      private_key:
        required: true
        type: string
        description: "The name of the app to push to"
      image_name:
        required: true
        type: string
        description: "The name of the image to push"

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Push
        uses: dokku/github-action@v1.4.0
        with:
          git_remote_url: ${{ inputs.remote_url }}
          ssh_private_key: ${{ secrets.private_key }}
          deploy_docker_image: ${{ inputs.image_name }}
