name: Push to Dokku

on:
  workflow_call:
    inputs:
      git_remote_url:
        required: true
        type: string
        description: "The remote URL to push to"
      deploy_docker_image:
        required: true
        type: string
        description: "The name of the image to push"

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Push
        uses: dokku/github-action@v1.7.0
        with:
          git_remote_url: ${{ inputs.git_remote_url }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: ${{ inputs.deploy_docker_image }}
