name: Techlab Blog | Deploy Dev

on:
  push:
    branches: [ft/techlabblog-workflow]
    paths:
      - "apps/techlabblog/**"
      - "Dockerfile"
      - ".github/workflows/techlabblog-deploy-dev.yml"

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

env:
  SENTRY_ENVIRONMENT: "development"

jobs:
  env-setup:
    name: Environment Setup
    runs-on: ubuntu-latest
    outputs:
      SENTRY_ENVIRONMENT: ${{ steps.env-setup.outputs.SENTRY_ENVIRONMENT }}
    steps:
      - name: Environment Setup
        id: env-setup
        run: |
          echo "SENTRY_ENVIRONMENT=${{ env.SENTRY_ENVIRONMENT }}" >> $GITHUB_ENV

  build-docker-image:
    name: Build Docker Image
    needs: [env-setup]
    uses: ./.github/workflows/build-docker-image.yml
    secrets: inherit
    with:
      tags: "codeforafrica/techlabblog:${{ github.sha }}"
      target: "techlabblog-runner"
      build_args: |
        SENTRY_ENVIRONMENT=${{ needs.env-setup.outputs.SENTRY_ENVIRONMENT }}
        SENTRY_DSN: ${{ vars.TECHLABBLOG_SENTRY_DSN }}

  push-to-dokku:
    name: Push to Dokku
    needs: [build-docker-image, env-setup]
    uses: ./.github/workflows/push-to-dokku.yml
    secrets: inherit
    with:
      remote_url: "ssh://azureuser@ui-1.dev.codeforafrica.org/techlabblog"
      image_name: "codeforafrica/techlabblog:${{ github.sha }}"
