name: TechLab Blog | Deploy | DEV

on:
  push:
    branches:
      - main

    paths:
      - "apps/techlabblog/**"
      - "Dockerfile"
      - ".github/workflows/techlabblog-deploy-dev.yml"

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

env:
  APP_NAME: techlabblog-ui
  DOKKU_REMOTE_BRANCH: "master"
  DOKKU_REMOTE_URL: "ssh://azureuser@ui-1.dev.codeforafrica.org"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: "codeforafrica/techlabblog-ui"
  NEXT_PUBLIC_APP_URL: "https://techlabblog-ui.dev.codeforafrica.org"
  SENTRY_ENVIRONMENT: "development"

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.16]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Add support for more platforms with QEMU (optional)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          path: /tmp/.buildx-cache
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            NEXT_PUBLIC_APP_URL=${{ env.NEXT_PUBLIC_APP_URL }}
            NEXT_PUBLIC_SENTRY_DSN=${{ secrets.TECHLABBLOG_SENTRY_DSN }}
            SENTRY_ENVIRONMENT=${{ env.SENTRY_ENVIRONMENT }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          context: .
          platforms: linux/arm64
          push: true
          secrets: |
            "sentry_auth_token=${{ secrets.SENTRY_AUTH_TOKEN }}"
            "sentry_org=${{ secrets.SENTRY_ORG }}"
            "sentry_project=${{ secrets.TECHLABBLOG_SENTRY_PROJECT }}"
          tags: "${{ env.IMAGE_NAME }}:${{ github.sha }}"
          target: techlabblog-runner

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Push to Dokku
        # We don't have DEV techlabblog app on ui-1 DEV
        # TODO(xavier): Confirm if we need this or not.
        if: false
        uses: dokku/github-action@v1.7.0
        with:
          git_remote_url: ${{ env.DOKKU_REMOTE_URL }}/${{ env.APP_NAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
