name: Techlab Blog | Deploy Dev

on:
  push:
    branches: [ft/techlabblog-workflow]
    paths:
      - "apps/techlabblog/**"
      - "Dockerfile"
      - ".github/workflows/techlabblog-deploy-dev.yml"

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

env:
  DOKKU_REMOTE_URL: "ssh://azureuser@ui-1.dev.codeforafrica.org/techlabblog"
  IMAGE_NAME: "codeforafrica/techlabblog"
  SENTRY_ENVIRONMENT: "development"

jobs:
  build-docker-image:
    uses: ./.github/workflows/build-docker-image.yml
    secrets: inherit
    with:
      tags: "${{ env.IMAGE_NAME }}:${{ github.sha }}"
      target: "techlabblog"
      build_args: |
        SENTRY_DSN=${{ secrets.TECHLABBLOG_SENTRY_DSN }}
        SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ENVIRONMENT=${{ env.SENTRY_ENVIRONMENT }}
        SENTRY_ORG=${{ secrets.SENTRY_ORG }}

  # push-to-dokku:
  #   secrets: inherit
  #   uses: ./.github/workflows/push-to-dokku.yml
  #   with:
  #     remote_url: ${{ env.DOKKU_REMOTE_URL }}
  #     private_key: ${{ secrets.DOKKU_PRIVATE_KEY }}
  #     image_name: "${{ env.IMAGE_NAME }}:${{ github.sha }}"
