name: Techlab Blog | Deploy Dev

on:
  push:
    branches: [ft/techlabblog-workflow]
    paths:
      - "apps/techlabblog/**"
      - "Dockerfile"
      - ".github/workflows/techlabblog-deploy-dev.yml"

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

env:
  DOKKU_REMOTE_URL: "ssh://azureuser@ui-1.dev.codeforafrica.org/techlabblog"
  IMAGE_NAME: "codeforafrica/techlabblog"
  SENTRY_ENVIRONMENT: "development"

jobs:
  env-setup:
    runs-on: ubuntu-latest
    outputs:
      DOKKU_REMOTE_URL: ${{ steps.env-setup.outputs.DOKKU_REMOTE_URL }}
      DOKKU_PRIVATE_KEY: ${{ steps.env-setup.outputs.DOKKU_PRIVATE_KEY }}
      IMAGE_NAME: ${{ steps.env-setup.outputs.IMAGE_NAME }}
      SENTRY_ORG: ${{ steps.env-setup.outputs.SENTRY_ORG }}
      SENTRY_DSN: ${{ steps.env-setup.outputs.SENTRY_DSN }}
      SENTRY_AUTH_TOKEN: ${{ steps.env-setup.outputs.SENTRY_AUTH_TOKEN }}
      SENTRY_ENVIRONMENT: ${{ steps.env-setup.outputs.SENTRY_ENVIRONMENT }}
    steps:
      - name: Environment Setup
        id: env-setup
        run: |
          echo "DOKKU_REMOTE_URL=${{env.DOKKU_REMOTE_URL}}" >> $GITHUB_ENV
          # Multi-line string: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#multiline-strings
          echo "SSH_PRIVATE_KEY<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
          echo "SENTRY_ORG=${{ secrets.SENTRY_ORG }}" >> $GITHUB_ENV
          echo "SENTRY_DSN=${{ secrets.TECHLABBLOG_SENTRY_DSN }}" >> $GITHUB_ENV
          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> $GITHUB_ENV
          echo "SENTRY_ENVIRONMENT=${{ env.SENTRY_ENVIRONMENT }}" >> $GITHUB_ENV

  build-docker-image:
    needs: [env-setup]
    uses: ./.github/workflows/build-docker-image.yml
    secrets: inherit
    with:
      tags: "${{needs.env-setup.outputs.IMAGE_NAME}}:${{ github.sha }}"
      target: "techlabblog-runner"
      build_args: |
        SENTRY_AUTH_TOKEN=${{ needs.env-setup.outputs.SENTRY_AUTH_TOKEN }}
        SENTRY_ENVIRONMENT=${{ needs.env-setup.outputs.SENTRY_ENVIRONMENT }}
        SENTRY_ORG: ${{ needs.env-setup.outputs.SENTRY_ORG }}
        SENTRY_DSN: ${{ needs.env-setup.outputs.SENTRY_DSN }}

  push-to-dokku:
    needs: [build-docker-image, env-setup]
    secrets: inherit
    uses: ./.github/workflows/push-to-dokku.yml
    with:
      remote_url: ${{ needs.env-setup.outputs.DOKKU_REMOTE_URL }}
      private_key: ${{ needs.env-setup.outputs.DOKKU_PRIVATE_KEY }}
      image_name: ${{needs.env-setup.outputs.IMAGE_NAME}}:${{ github.sha }}
