name: Techlab Blog | Deploy Dev

on:
  push:
    branches: [ft/techlabblog-workflow]
    paths:
      - "apps/techlabblog/**"
      - "Dockerfile"
      - ".github/workflows/techlabblog-deploy-dev.yml"

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

env:
  DOKKU_REMOTE_URL: "ssh://azureuser@ui-1.dev.codeforafrica.org/techlabblog"
  IMAGE_NAME: "codeforafrica/techlabblog"
  SENTRY_ENVIRONMENT: "development"

jobs:
  build-docker-image:
    uses: ./.github/workflows/build-docker-image.yml
    secrets: inherit
    with:
      tags: "codeforafrica/techlabblog:${{ github.sha }}"
      target: "techlabblog"
      build_args: |
        SENTRY_DSN=$env:TECHLABBLOG_SENTRY_DSN
        SENTRY_AUTH_TOKEN=$env:SENTRY_AUTH_TOKEN
        SENTRY_ENVIRONMENT=$env:SENTRY_ENVIRONMENT
        SENTRY_ORG: $secrets:SENTRY_ORG

  push-to-dokku:
    needs: [build-docker-image]
    secrets: inherit
    uses: ./.github/workflows/push-to-dokku.yml
    with:
      remote_url: "ssh://azureuser@ui-1.dev.codeforafrica.org/techlabblog"
      private_key: $secrets.DOKKU_PRIVATE_KEY
      image_name: "codeforafrica/techlabblog:${{ github.sha }}"
