name: TrustLab | Deploy | PROD

on:
  push:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

env:
  APP_NAME: trustlab-ui
  DOKKU_REMOTE_BRANCH: "master"
  DOKKU_REMOTE_URL: "ssh://dokku@ui-2.prod.codeforafrica.org"
  GIT_PUSH_FLAGS: "--force"
  IMAGE_NAME: "codeforafrica/${{ env.APP_NAME }}"
  VERSION_FILE_NAME: "./apps/trustlab/package.json"
  NEXT_PUBLIC_APP_URL: "https://trustlab.africa"
  SENTRY_ENVIRONMENT: "production"

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [24.11]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Add support for more platforms with QEMU (optional)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check if version is bumped
        id: version-check
        uses: EndBug/version-check@v2
        with:
          # Whether to search in every commit's diff.
          # This is useful if you often do change the version without saying it
          # in the commit message. If you always include the semver of the new
          # version in your commit message when you bump versions then you can
          # omit this.
          diff-search: true
          file-name: "${{ env.VERSION_FILE_NAME }}"

      - name: Set up Docker Buildx
        if: steps.version-check.outputs.changed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        if: steps.version-check.outputs.changed == 'true'
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          path: /tmp/.buildx-cache
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        if: steps.version-check.outputs.changed == 'true'
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Build Docker image
        if: steps.version-check.outputs.changed == 'true'
        uses: docker/build-push-action@v6
        with:
          build-args: |
            PAYLOAD_CORS=${{ vars.TRUSTLAB_PAYLOAD_CORS }}
            PAYLOAD_CSRF=${{ vars.TRUSTLAB_PAYLOAD_CSRF }}
            NEXT_PUBLIC_APP_URL=${{ env.NEXT_PUBLIC_APP_URL }}
            NEXT_PUBLIC_SENTRY_DSN=${{ secrets.TRUSTLAB_SENTRY_DSN }}
            SENTRY_ENVIRONMENT=${{ env.SENTRY_ENVIRONMENT }}
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max
          context: .
          platforms: linux/arm64
          push: true
          secrets: |
            "mongo_url=${{ secrets.TRUSTLAB_MONGO_URL }}"
            "payload_secret=${{ secrets.TRUSTLAB_PAYLOAD_SECRET }}"
            "sentry_auth_token=${{ secrets.SENTRY_AUTH_TOKEN }}"
            "sentry_org=${{ secrets.SENTRY_ORG }}"
            "sentry_project=${{ secrets.TRUSTLAB_SENTRY_PROJECT }}"
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.version-check.outputs.version }}
          target: trustlab-runner

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        if: steps.version-check.outputs.changed == 'true'
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Push to Dokku
        if: steps.version-check.outputs.changed == 'true'
        uses: dokku/github-action@v1.9.0
        with:
          git_remote_url: ${{ env.DOKKU_REMOTE_URL }}/${{ env.APP_NAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: ${{ env.IMAGE_NAME }}:${{ steps.version-check.outputs.version }}
