name: VPN Manager | Deploy | DEV

on:
  push:
    branches:
      - main

    paths:
      - "apps/vpnmanager/**"
      - "Dockerfile.vpnmanager"
      - ".github/workflows/vpnmanager-deploy-prod.yml"

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

env:
  DOKKU_REMOTE_URL: "ssh://ubuntu@ui-2.prod.codeforafrica.org/vpnmanager-ui"
  IMAGE_NAME: "codeforafrica/vpnmanager-ui"
  SENTRY_ENVIRONMENT: "production"
  VERSION_FILE_NAME: "./apps/vpnmanager/package.json"

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.16]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check if version is bumped
        id: version-check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          file-name: "${{ env.VERSION_FILE_NAME }}"

      # Add support for more platforms with QEMU (optional)
      - name: Set up QEMU
        if: steps.version-check.outputs.changed == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: steps.version-check.outputs.changed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        if: steps.version-check.outputs.changed == 'true'
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          path: /tmp/.buildx-cache
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        if: steps.version-check.outputs.changed == 'true'
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Build Docker image
        if: steps.version-check.outputs.changed == 'true'
        uses: docker/build-push-action@v6
        with:
          build-args: |
            NEXT_PUBLIC_SENTRY_DSN=${{ secrets.VPNMANAGER_SENTRY_DSN }}
            SENTRY_ENVIRONMENT=${{ env.SENTRY_ENVIRONMENT }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          context: .
          platforms: linux/arm64
          push: true
          secrets: |
            "api_secret_key=${{ secrets.VPNMANAGER_API_SECRET_KEY }}"
            "sentry_auth_token=${{ secrets.SENTRY_AUTH_TOKEN }}"
            "sentry_org=${{ secrets.SENTRY_ORG }}"
            "sentry_project=${{ secrets.VPNMANAGER_SENTRY_PROJECT }}"
          tags: "${{ env.IMAGE_NAME }}:${{ github.sha }}"
          target: vpnmanager-runner

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        if: steps.version-check.outputs.changed == 'true'
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Push to Dokku
        if: steps.version-check.outputs.changed == 'true'
        uses: dokku/github-action@v1.7.0
        with:
          git_remote_url: ${{ env.DOKKU_REMOTE_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
